# https://docs.travis-ci.com/user/languages/android
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23

    # specify emulator to run during your tests
    - sys-img-armeabi-v7a-android-23

  licenses:
    - 'android-sdk-license-.+'
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

install:
  - npm install -g npm@2
  - npm install react-native@0.34 -dd

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window -memory 2048 -partition-size 2048 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: travis_wait 30 ./gradlew build connectedCheck --stacktrace

jdk: oraclejdk7
sudo: false
notifications:
  email:
    - spatialconnect@boundlessgeo.com
